### ISSUE TITLE
Update content for Oct 2022 workshop

### ISSUE THREAD

**Issue by mwakok** [mwakok/software_carpentries#8]
- [ ] ~Add data processing with pandas~
- [ ] ~Move numpy focus to n-dimension arrays?~
- [x] Remove Python CLI
- [ ] ~Work towards executable file to be used in Unix lesson~
- [ ] ~Explore research narrative --> How can we set up a workflow to get to a reproducible paper?~
- [ ] ~Add information on creating slides from jupyter notebooks~
- [x] Create exercise notebooks
- [x] Add homework exercises to exercise notebooks

**Comment by wmotion** [comment]
Would you create a new tag when the material for the workshop is ready please? This can be instructive for the students who use Git afterwards. Thanks.
